name: Design New Feature
description: Create design documents for a new game mechanic or feature (for non-developers)
title: "[Design] "
labels: ["design"]
body:
  - type: markdown
    attributes:
      value: |
        ## Design New Feature

        Describe the game mechanic or feature you want to apply to the system. Focus on **what** should happen - Claude will handle the technical details and test creation.

        **You don't need to know:**
        - Which architecture layers to use (Entity/System/Renderer)
        - How to write test cases (Claude will create them)
        - Technical implementation details

        **Just describe:**
        - What behavior you want to add
        - How it should work from the player's perspective

        **Tip:** You can add more details later using the "Clarify Design" issue template.

  - type: input
    id: claude_command
    attributes:
      label: Claude Command
      description: This field tells Claude Code which command to execute (do not modify)
      value: "/design"
    validations:
      required: true

  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      description: Short name for this feature (e.g., "Bird Physics", "Collision Detection")
      placeholder: "e.g., Bird Physics"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Detailed explanation of the desired behavior. Focus on WHAT it should do, not HOW.
      placeholder: |
        Describe what you want this feature to do:

        **Behavior:**
        - What should happen when the user interacts?
        - What visual/audio feedback should occur?
        - How should the game state change?

        **Examples:**
        - "The bird should fall continuously due to gravity"
        - "When the player taps, the bird should jump upward"
        - "Play a sound effect when the bird jumps"

        You can add more details later via clarify issues if needed.
    validations:
      required: true

  - type: input
    id: related_issues
    attributes:
      label: Related Issues (Optional)
      description: Reference related issues for additional context
      placeholder: "#123, #456"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Any other information, constraints, or examples that might help

  - type: markdown
    attributes:
      value: |
        ---

        ## Claude Command

        This issue will trigger: `/design [feature name]`

        ## Next Steps

        After submitting this issue:
        1. Add a comment with `@claude` to trigger the design process
        2. Claude will create design documents based on your description
        3. Claude will generate BDD test scenarios automatically
        4. You'll receive a summary of what was created
        5. Use the "Clarify Design" template if you need to add more details
