/**
 * Event Definitions
 *
 * This module exports all event types used in the game engine.
 * Events are categorized into:
 * - SystemEvents: Generated by the engine or external systems (PixiJS, input adapters)
 * - GameEvents: Dispatched by game systems to modify game state
 */

export * from "./GameEvents";
export * from "./SystemEvents";

import type { GameEvent } from "./GameEvents";
import type { SystemEvent } from "./SystemEvents";

/**
 * Union type of all possible events in the game
 */
export type Event = SystemEvent | GameEvent;
