/**
 * System-level event definitions for internal engine communication.
 * @see {@link ../../docs/ARCHITECTURE.md|Architecture - Event Flow}
 */

/**
 * System Events
 *
 * Events generated by the engine or external systems (PixiJS, input adapters)
 * that drive the game loop and user interactions.
 */

/**
 * System event type enum
 */
export enum SystemEventType {
  Tick = "TICK",
  KeyDown = "KEY_DOWN",
  MouseClick = "MOUSE_CLICK",
}

/**
 * TICK event
 *
 * The main game loop event that triggers physics calculations every frame.
 */
export interface TickEvent {
  type: SystemEventType.Tick;
  payload: {
    /** Frame time multiplier (1.0 = 60fps target frame). From PixiJS Ticker.deltaTime */
    deltaTime: number;
  };
}

/**
 * KEY_DOWN event
 *
 * Triggered when the player presses a key on the keyboard.
 */
export interface KeyDownEvent {
  type: SystemEventType.KeyDown;
  payload: {
    /** The key code or name (e.g., "Space", "Enter") */
    key: string;
  };
}

/**
 * MOUSE_CLICK event
 *
 * Triggered when the player clicks the mouse anywhere on the game canvas.
 */
export interface MouseClickEvent {
  type: SystemEventType.MouseClick;
  payload: {
    /** X coordinate of the mouse click position */
    x: number;
    /** Y coordinate of the mouse click position */
    y: number;
  };
}

/**
 * Union type of all system events
 */
export type SystemEvent = TickEvent | KeyDownEvent | MouseClickEvent;
